### ISSUE TITLE
Support for multiple datasources

### ISSUE THREAD

**Issue by tiagodolphine** [quarkiverse/quarkus-embedded-postgresql#20]
When the application has multliple datasources for postgresql db-kind it should be possible to make the extension handle all of these datasources that might have set different database and URLs,  for each of one them.

For example, a given application might contain these datasources:
- runtime 
- job-service
- data-index

For each of them, flyway may be used to control the schema creation, so in this kind of use case just the default datasource it not viable.

**Comment by fjtirado** [comment]
I think than before exploring having three different databases (which will lead with issues with quarkus.datasource.jdbc.url), we should first try using three different schemas.
Flyway should be able to handle that through [quarkus.flyway.schemas](https://quarkus.io/guides/flyway#quarkus-flyway_quarkus.flyway.schemas)

**Comment by tiagodolphine** [comment]
data.dir would remain the same, we continue to have just one single instance of PostgreSQL running, the idea is just to create different databases in this instance, one for each datasource. The instance uses just one data.dir

**Comment by fjtirado** [comment]
@tiagodolphine Yes, I know thats the idea ;). Lets see if it is feasible.

**Comment by tiagodolphine** [comment]
@fjtirado yeah let's see I working on some impl and tests with it and I'll open a PR a soon as I have something working in this way you can give your feedback and we come up with a good solution, and the idea is to keep the current behavior in case there is no "named" datasoruces, just the default one.

**Comment by cristianonicolai** [comment]
Resolved by https://github.com/quarkiverse/quarkus-embedded-postgresql/pull/22
