### ISSUE TITLE
DevUI: Add Card

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-embedded-postgresql#71]
You can assign this to me. 

- [x] DevUI card displaying PostGres DB info
- [x] DevServices information about connected DB

![image](https://github.com/quarkiverse/quarkus-embedded-postgresql/assets/4399574/b022f34b-ad57-4e38-907a-3b21322663f4)

**Comment by phillip-kruger** [comment]
Normal config related to an extension can be seen in the config screen when navigation there from the extension card. It will use the filter value in the extension yaml and filter the navigation screen accordingly

**Comment by melloware** [comment]
Oh I forgot to mention this is an embedded service so its not a REAL Container Dev Service is running embedded DB.  So like in Quinoa we do this to put the "fake" DevService in the list for Node.js.  I was hoping to do something similar here.

```java
 @BuildStep
    void registerDevServices(BuildProducer<DevServicesResultBuildItem> devServices) {
        Map<String, String> devServerConfigMap = new LinkedHashMap<>();
        Config config = ConfigProviderResolver.instance().getConfig();
        for (String propertyName : config.getPropertyNames()) {
            if (propertyName.startsWith("quarkus.datasource.")) {
                devServerConfigMap.put(propertyName, config.getConfigValue(propertyName).getValue());
            }
        }

        DevServicesResultBuildItem.RunningDevService devService = new DevServicesResultBuildItem.RunningDevService(
                FEATURE, null, null, devServerConfigMap);
        devServices.produce(devService.toBuildItem());
    }
```

**Comment by melloware** [comment]
No at runtime it dynamically assigns to `quarkus.datasource.jdbc.url` to `jdbc:postgresql://localhost:60290/postgres`

**Comment by melloware** [comment]
It looks like its only has build time properties that are in the application.properties when I ask `ConfigProvider`.

**Comment by melloware** [comment]
I guess the question is how is it possible to have the DevServices info use Runtime values?

**Comment by melloware** [comment]
No problem!  Yeah I got the DevUI card using a JsonRpcService to get the port and running URL but was wondering how to jam it on DevServices too.

**Comment by phillip-kruger** [comment]
I don't think this is possible at the moment. The dev services is built time data. We would need to change that to jsonrpc to get run time data. Or maybe a mix / config that allows this.

**Comment by melloware** [comment]
No worries I think based on the other ticket I am going to end up making this a build time config anyway to refactor for the 3.6.0 issues
